### ISSUE TITLE
What are the limitations?

### ISSUE THREAD

**Issue by luwes** [apivideo/blobUpload#2]
I uploaded a test video the other day for a video benchmark at https://dev.playerx.io
This is the test video: https://www.dropbox.com/s/w2f25m0kr2hv036/The%20World%20In%20HDR%204K.mp4?dl=0

Today it seemed to be removed at https://embed.api.video/vod/vi7TzXJxXZB1J1pHCSUTVHXZ

Are there any limitations with the service at https://upload.a.video/ ?

**Comment by egobillot** [comment]
Hello, 

https://upload.a.video is just for people to test our service. We regularly delete the video uploaded. 
I have downloaded your test video and uploaded it with a production account. It will not be deleted automatically.
Your video is here : https://go.api.video/videos/viM0Q6S2LqkdI8D7RqTDsBG

Good benchmark ;-)

**Comment by luwes** [comment]
Thank you @egobillot! 

Added apivideo to the matrix too, great performance, maybe lacking video quality a bit from first tests compared to others.
https://dev.playerx.io/matrix/
